trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  chart.name: osm-arc
  chart.path: $(System.DefaultWorkingDirectory)/charts/$(chart.name)
  image.dir: $(Build.ArtifactStagingDirectory)
  image.artifact.name: drop

stages:
  - stage: run_openshift_upgrade_e2e
    jobs:
      - job: test_openshift_upgrade_e2e
        pool: staging-pool
        workspace:
          clean: all
        steps:
          - template: templates/install-helm3.yaml
          - template: templates/install-oras.yaml
          - template: templates/package-helm-chart.yaml
          - template: templates/publish-helm-chart.yaml
            parameters:
              releaseTag: "True"
          - bash: ./scripts/test-openshift-upgrade.sh
          - template: templates/acr-cleanup.yaml
          - bash: |
              az group list --query "[?tags.team == 'osmarc'].name" -o tsv |
                  xargs -rn 1 az group delete -y --no-wait -n
            displayName: Delete OSM Arc testing resource groups
            condition: always()
